<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["dev"]["*"]="D";
$PERM["sale"]["*"]="R";
$PERM["projects"]["*"]="D";
$PERM["blog"]["*"]="R";
$PERM["robots.txt"]["20"]="W";
$PERM["robots.txt"]["8"]="W";
$PERM["tests"]["*"]="D";
$PERM["stavropol"]["*"]="R";
$PERM["bitrix"]["18"]="R";
$PERM["personal"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["/"]["*"]="R";
$PERM["vkparse"]["*"]="R";
$PERM["vkparse"]["1"]="X";
$PERM["coins_work"]["*"]="D";
$PERM["coins_work"]["1"]="X";
$PERM["ses_log_jeiorjioashdf"]["*"]="D";
$PERM["ses_log_jeiorjioashdf"]["1"]="X";
$PERM["ses_tools"]["*"]="D";
?>