version: '3'

networks:
  router:
    external:
      name: router

volumes:
  fs_database:
services:

  app:
    build: docker/mysql
    env_file: .env
    environment:
      DATABASE_HOST: database
    links:
      - database
    volumes:
      - './docker/php.ini:/usr/local/etc/php/php.ini'
      - ./:/var/www/html/:delegated
      - './docker/bootstrap.sh:/init.sh'

  nginx:
    image: nginx
    labels:
      traefik.enable: '1'
      traefik.frontend.rule: Host:sti.box
      traefik.docker.network: router
    networks:
      - router
      - default
    links:
      - app
    volumes:
      - ./:/var/www/html:delegated
      - './docker/nginx.conf:/etc/nginx/nginx.conf'
  database:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
